### ISSUE TITLE
Can I replace resnet50?

### ISSUE THREAD

**Issue by fuziwang** [filby89/body-face-emotion-recognition#1]
hi, if i want to replace resnet50, what can i do?

**Comment by filby89** [comment]
Hi, due to the fact that the database contains sensitive children data we can only offer extracted resnet50 CNN features (included here: https://zenodo.org/record/3233060). If you want to apply the project to a new database, you have to retrain another CNN on affectnet and use it to extract features in your data. 
For BRED, we do not currently plan to release CNN features from another architecture.

**Comment by fuziwang** [comment]
Ok, thank you very much! Fortunately, you have provided the corresponding csv and joint data. I would like to ask, what is the current sota of this dataset. At present, I see that the dataset is only used by your work.

**Comment by filby89** [comment]
I am not aware of any other works using the BRED dataset! However, I have not done a thorough search of this. You could also check [here](https://scholar.google.com/scholar?start=10&hl=en&as_sdt=2005&sciodt=0,5&cites=14712499343308431683&scipsc=) to see if there are others using it!

**Comment by fuziwang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
