### ISSUE TITLE
Questions about the algorithm

### ISSUE THREAD

**Issue by ctxmc** [filby89/body-face-emotion-recognition#3]
Hey Filntisis,

greetings from Brasil!

I'm a computer science student currently cursing Image Processing class at my university.

In that class we need to reproduce a experiment of emotion recognition.

My team theme its about recognition at surveillance cameras.

To do so, we thought that process emotion from body, instead of face, in a surveillance camera context it's better than the face,
because in that context, we can't get good angules of face as well. 

I got to your algorithm and paper, and it's really impressive work! We are using you as reference, and we agree about using the 
body as a remarkable point in emotion recognition. As we are just normal students our paper will never see the light of sun of 
science publication, but we are doing a little hard work haha.

I want to know, if your algorithm is capable of process multiple subjects instead of one.

I have a surveillance camera dataset, wich is just a video colletion with no annotations on it:
https://viratdata.org/

To do so, I must use openface and openpose to convert that video data into keypoints, and I must do the annotations 
by myself? Or, after training the algorithm with your dataset, I can insert that data flow and get a new output based on
the data collected there?

Thank you very much!

**Comment by filby89** [comment]
Hi @dostoievsky, thank you for your interest in our work !
I think that the best approach is to process each subject in your videos individually:

* Run openpose and collect all skeletons. Then crop around each skeleton a bounding box in order to get a subject specific image.
* Run openface on the bounding box and crop the face in order to feed it into the .  
* You will need to do manual annotation for each image (the emotion it depicts). We have used ELAN for annotation (https://archive.mpi.nl/tla/elan) however maybe there are newer easier tools for annotation.

Then, at training time use each annotated subject as a different sample (even if the belong in the same image).
At inference time for each frame in the test set detect all people in the frame (again openpose, openface) and perform inference for each one separately.

You can also use the model trained with the BRED dataset to just perform inference in your subjects (one at a time) and see how it goes (before annotating your dataset).

**Comment by ctxmc** [comment]
@filby89, thank you very much for you answer, I'll try do experiments with your code as you suggested me! I'll close this issue, since the questions I had are answered and I think I can work with that!
